







```{r, include=FALSE, warning = FALSE, message=FALSE, cache=TRUE}
##    Prep data for figures:  
      exp3__hits__data <- as.tibble(emmeans(exp3__grey__anova__PROP.HITS, ~ stim_format)) %>%
          select(stim_format, emmean, SE) %>%
          filter(stim_format != "Words") %>%
          mutate(stim_format = str_replace(stim_format, "Drawings", "Grey Drawings")) %>%
          mutate(stim_format = str_replace(stim_format, "Photographs", "Grey Photographs"))
      exp4__hits__data <- as.tibble(emmeans(exp4__anova_prop_hit, ~ stim_format)) %>%
          select(stim_format, emmean, SE) %>%
          filter(stim_format != "Words") %>%
          mutate(stim_format = str_replace(stim_format, "Drawings", "Colour Drawings")) %>%
          mutate(stim_format = str_replace(stim_format, "Photographs", "Colour Photographs"))
      exp3.and.exp4__hits__data <- bind_rows(exp3__hits__data, exp4__hits__data) %>%
          mutate(DV = "Hits")
      
      exp3__FA__data <- as.tibble(emmeans(exp3__grey__anova__PROP.FA, ~ stim_format)) %>%
          select(stim_format, emmean, SE) %>%
          filter(stim_format != "Words") %>%
          mutate(stim_format = str_replace(stim_format, "Drawings", "Grey Drawings")) %>%
          mutate(stim_format = str_replace(stim_format, "Photographs", "Grey Photographs"))
      exp4__FA__data <- as.tibble(emmeans(exp4__anova_prop_FA, ~ stim_format)) %>%
          select(stim_format, emmean, SE) %>%
          filter(stim_format != "Words") %>%
          mutate(stim_format = str_replace(stim_format, "Drawings", "Colour Drawings")) %>%
          mutate(stim_format = str_replace(stim_format, "Photographs", "Colour Photographs"))
      exp3.and.exp4__FA__data <- bind_rows(exp3__FA__data, exp4__FA__data) %>%
          mutate(DV = "FAs")
      
      exp3__recog__data <- as.tibble(emmeans(exp3__grey__anova__RECOG, ~ stim_format)) %>%
          select(stim_format, emmean, SE) %>%
          filter(stim_format != "Words") %>%
          mutate(stim_format = str_replace(stim_format, "Drawings", "Grey Drawings")) %>%
          mutate(stim_format = str_replace(stim_format, "Photographs", "Grey Photographs"))
      exp4__recog__data <- as.tibble(emmeans(exp4__anova_recog, ~ stim_format)) %>%
          select(stim_format, emmean, SE) %>%
          filter(stim_format != "Words") %>%
          mutate(stim_format = str_replace(stim_format, "Drawings", "Colour Drawings")) %>%
          mutate(stim_format = str_replace(stim_format, "Photographs", "Colour Photographs"))
      exp3.and.exp4__recog__data <- bind_rows(exp3__recog__data, exp4__recog__data) %>%
          mutate(DV = "Overall recognition accuracy")
    
      exp3.and.exp4__figure.data <- bind_rows(exp3.and.exp4__hits__data, exp3.and.exp4__FA__data, 
                                              exp3.and.exp4__recog__data) %>%
          separate(., stim_format, into = c("Distinctiveness", "stim_format"), sep = "\\s", extra = "merge") %>%
          transform(DV = factor(DV, levels=c("Hits","FAs", "Overall recognition accuracy"))) %>%
          transform(stim_format = factor(stim_format, levels=c("Drawings", "Photographs"))) %>%
          transform(Distinctiveness = factor(Distinctiveness, levels=c("Grey","Colour")))
      
      exp3.and.exp4__figure <-
          ggplot(exp3.and.exp4__figure.data, aes(x = stim_format, y = emmean, fill = Distinctiveness)) +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", 
                                                 "Colour" = "#6A6C93")) + 
          geom_col(position = position_dodge()) +
          geom_errorbar(aes(ymin = pmax(emmean-SE, 0), ymax = emmean+SE), 
                        width = 0.2, size = 0.3, position = position_dodge(0.9)) +
          facet_wrap(~DV, strip.position = "bottom") +
          labs(x = "DV", y = "Mean proportion") +
          scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
          theme_classic() +    # Removes grey background and grid lines. 
          theme(strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-4),    # Move x-axis label further away from the figure.
                axis.title.y = element_text(vjust=6),     # Move y-axis label further away from the figure.
                axis.text.x = element_text(size = 9),
                axis.text.y = element_text(size = 9),
                legend.background = element_rect(fill = "white", size = 0.2, linetype = "solid", colour = "black"),
                legend.title = element_blank(),
                legend.position = c(0.5, 0.896),
                legend.margin = margin(6, 6, 6, 6),
                legend.spacing.y = unit(-1, "pt"),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(20, 20, 24, 30))
```


```{r, include=FALSE, warning = FALSE, message=FALSE, cache=TRUE}
##    Rec hits:
      exp3__prop_drawing_hit_rec <- exp3__final.data %>%
          select(prop_drawing_hit_rec) %>%
          rename(Grey = "prop_drawing_hit_rec") %>%
          gather(key = "Response", value = "Hits")
      exp4__prop_drawing_hit_rec <- exp4__colour_data %>%
          select(prop_drawing_hit_rec) %>%
          rename(Colour = "prop_drawing_hit_rec") %>%
          gather(key = "Response", value = "Hits")
      exp3.vs.exp4__rec.hits.data <- bind_rows(exp3__prop_drawing_hit_rec, exp4__prop_drawing_hit_rec)
##    Fam hits:
      exp3__prop_drawing_hit_fam <- exp3__final.data %>%
          select(prop_drawing_hit_fam) %>%
          rename(Grey = "prop_drawing_hit_fam") %>%
          gather(key = "Response", value = "Hits")
      exp4__prop_drawing_hit_fam <- exp4__colour_data %>%
          select(prop_drawing_hit_fam) %>%
          rename(Colour = "prop_drawing_hit_fam") %>%
          gather(key = "Response", value = "Hits")
      exp3.vs.exp4__fam.hits.data <- bind_rows(exp3__prop_drawing_hit_fam, exp4__prop_drawing_hit_fam)
##    Guess hits:
      exp3__prop_drawing_hit_guess <- exp3__final.data %>%
          select(prop_drawing_hit_guess) %>%
          rename(Grey = "prop_drawing_hit_guess") %>%
          gather(key = "Response", value = "Hits")
      exp4__prop_drawing_hit_guess <- exp4__colour_data %>%
          select(prop_drawing_hit_guess) %>%
          rename(Colour = "prop_drawing_hit_guess") %>%
          gather(key = "Response", value = "Hits")
      exp3.vs.exp4__guess.hits.data <- bind_rows(exp3__prop_drawing_hit_guess, exp4__prop_drawing_hit_guess)
      
##    Rec FAs:
      exp3__prop_drawing_FA_rec <- exp3__final.data %>%
          select(prop_drawing_FA_rec) %>%
          rename(Grey = "prop_drawing_FA_rec") %>%
          gather(key = "Response", value = "FAs")
      exp4__prop_drawing_FA_rec <- exp4__colour_data %>%
          select(prop_drawing_FA_rec) %>%
          rename(Colour = "prop_drawing_FA_rec") %>%
          gather(key = "Response", value = "FAs")
      exp3.vs.exp4__rec.FAs.data <- bind_rows(exp3__prop_drawing_FA_rec, exp4__prop_drawing_FA_rec)
##    Fam FAs:
      exp3__prop_drawing_FA_fam <- exp3__final.data %>%
          select(prop_drawing_FA_fam) %>%
          rename(Grey = "prop_drawing_FA_fam") %>%
          gather(key = "Response", value = "FAs")
      exp4__prop_drawing_FA_fam <- exp4__colour_data %>%
          select(prop_drawing_FA_fam) %>%
          rename(Colour = "prop_drawing_FA_fam") %>%
          gather(key = "Response", value = "FAs")
      exp3.vs.exp4__fam.FAs.data <- bind_rows(exp3__prop_drawing_FA_fam, exp4__prop_drawing_FA_fam)
##    Guess FAs:
      exp3__prop_drawing_FA_guess <- exp3__final.data %>%
          select(prop_drawing_FA_guess) %>%
          rename(Grey = "prop_drawing_FA_guess") %>%
          gather(key = "Response", value = "FAs")
      exp4__prop_drawing_FA_guess <- exp4__colour_data %>%
          select(prop_drawing_FA_guess) %>%
          rename(Colour = "prop_drawing_FA_guess") %>%
          gather(key = "Response", value = "FAs")
      exp3.vs.exp4__guess.FAs.data <- bind_rows(exp3__prop_drawing_FA_guess, exp4__prop_drawing_FA_guess)      
      
##    Plots:
      exp3.vs.exp4__rec.hits <- ggplot(exp3.vs.exp4__rec.hits.data, aes(x=Hits,y=Response,fill = Response))+
          geom_density_ridges(scale = 3, alpha=0.8) + 
          theme_ridges() +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          labs(x = "Recollection", y = "Stimuli format") +
          theme(legend.position = "none",
                strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-2, hjust = 0.5, size = 10),
                axis.title.y = element_text(vjust=4, hjust = 0.5, size = 10),
                axis.text.x = element_text(size = 10),
                axis.text.y = element_text(size = 10),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(20, 20, 24, 30))
      
      exp3.vs.exp4__fam.hits <- ggplot(exp3.vs.exp4__fam.hits.data, aes(x=Hits,y=Response,fill = Response))+
          geom_density_ridges(scale = 3, alpha=0.8) + 
          theme_ridges() +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          labs(x = "Familiarity", y = "Stimuli format") +
          theme(legend.position = "none",
                strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-2, hjust = 0.5, size = 10),
                axis.title.y = element_text(vjust=4, hjust = 0.5, size = 10),
                axis.text.x = element_text(size = 10),
                axis.text.y = element_text(size = 10),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(20, 20, 24, 30))
      
      exp3.vs.exp4__guess.hits <- ggplot(exp3.vs.exp4__guess.hits.data, aes(x=Hits,y=Response,fill = Response))+
          geom_density_ridges(scale = 3, alpha=0.8) + 
          theme_ridges() +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          scale_y_discrete(expand = c(0.01, 0)) +
          labs(x = "Guessing", y = "Stimuli format") +
          theme(legend.position = "none",
                strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-2, hjust = 0.5, size = 10),
                axis.title.y = element_text(vjust=4, hjust = 0.5, size = 10),
                axis.text.x = element_text(size = 10),
                axis.text.y = element_text(size = 10),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(20, 20, 24, 30))
      
      exp3.vs.exp4__rec.FAs <- ggplot(exp3.vs.exp4__rec.FAs.data, aes(x=FAs,y=Response,fill = Response))+
          geom_density_ridges(scale = 3, alpha=0.8) + 
          theme_ridges() +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          labs(x = "Recollection", y = "Stimuli format") +
          theme(legend.position = "none",
                strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-2, hjust = 0.5, size = 10),
                axis.title.y = element_text(vjust=4, hjust = 0.5, size = 10),
                axis.text.x = element_text(size = 10),
                axis.text.y = element_text(size = 10),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(20, 20, 24, 30))
        
      exp3.vs.exp4__fam.FAs <- ggplot(exp3.vs.exp4__fam.FAs.data, aes(x=FAs,y=Response,fill = Response))+
          geom_density_ridges(scale = 3, alpha=0.8) + 
          theme_ridges() +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          labs(x = "Familiarity", y = "Stimuli format") +
          theme(legend.position = "none",
                strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-2, hjust = 0.5, size = 10),
                axis.title.y = element_text(vjust=4, hjust = 0.5, size = 10),
                axis.text.x = element_text(size = 10),
                axis.text.y = element_text(size = 10),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(20, 20, 24, 30))
      
      exp3.vs.exp4__guess.FAs <- ggplot(exp3.vs.exp4__guess.FAs.data, 
                                        aes(x=FAs,y=Response, colour=Response, fill = Response)) +
          geom_density_ridges(scale = 3, alpha=0.8) + 
          theme_ridges() +
          scale_fill_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          scale_colour_manual("legend", values = c("Grey" = "#CCCCCC", "Colour" = "#6A6C93")) + 
          scale_y_discrete(expand = c(0.01, 0)) +
          labs(x = "Guessing", y = "Stimuli format") +
          theme(
                legend.position = "none",
                strip.placement = "outside",
                strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
                axis.title.x = element_text(vjust=-2, hjust = 0.5, size = 10),
                axis.title.y = element_blank(),
                axis.text.x = element_text(size = 10),
                axis.text.y = element_text(size = 10),
                plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
                plot.margin = margin(0, 0, 24, 0))
```

```{r, fig.height=6.4, echo=FALSE, warning = FALSE, message=FALSE, cache=TRUE}
      grid.arrange(exp3.vs.exp4__rec.hits, exp3.vs.exp4__rec.FAs,
                   exp3.vs.exp4__fam.hits, exp3.vs.exp4__fam.FAs,
                   exp3.vs.exp4__guess.hits, exp3.vs.exp4__guess.FAs,
                   ncol=2, nrow=3) #top = textGrob("Mean proportion of hits"))
```

```{r fig.width=7, fig.height=5.5, echo=FALSE, cache=TRUE}
      exp3.and.exp4__figure
```
`r figure_numbering("exp3.and.exp4__figure")`