---
output:
#  word_document:
#  toc: yes
#  toc_depth: '4'
    pdf_document:
        toc_depth: 4
        toc: yes
        number_sections: no
        fig_caption: yes
        latex_engine: xelatex
---
###################################################################################################################
##    Rec / Fam / Guess hits figure:                                                                             ##
###################################################################################################################
      exp1__hit_figure_data <- tribble(~"resp_optiononseOption", ~"stimuliFormat", ~"rfg", ~"emmean", ~"SE",
          as.character(pull(exp1__rec_hit_figure_data[1,1])), 
          as.character(pull(exp1__rec_hit_figure_data[1,2])), "Recollection",
          as.double(pull(exp1__rec_hit_figure_data[1,3])), as.double(pull(exp1__rec_hit_figure_data[1,4])),
          as.character(pull(exp1__rec_hit_figure_data[2,1])), 
          as.character(pull(exp1__rec_hit_figure_data[2,2])), "Recollection",
          as.double(pull(exp1__rec_hit_figure_data[2,3])), as.double(pull(exp1__rec_hit_figure_data[2,4])),
          as.character(pull(exp1__rec_hit_figure_data[3,1])), 
          as.character(pull(exp1__rec_hit_figure_data[3,2])), "Recollection",
          as.double(pull(exp1__rec_hit_figure_data[3,3])), as.double(pull(exp1__rec_hit_figure_data[3,4])),
          as.character(pull(exp1__rec_hit_figure_data[4,1])), 
          as.character(pull(exp1__rec_hit_figure_data[4,2])), "Recollection",
          as.double(pull(exp1__rec_hit_figure_data[4,3])), as.double(pull(exp1__rec_hit_figure_data[4,4])),
          as.character(pull(exp1__rec_hit_figure_data[5,1])), 
          as.character(pull(exp1__rec_hit_figure_data[5,2])), "Recollection",
          as.double(pull(exp1__rec_hit_figure_data[5,3])), as.double(pull(exp1__rec_hit_figure_data[5,4])),
          as.character(pull(exp1__rec_hit_figure_data[6,1])), 
          as.character(pull(exp1__rec_hit_figure_data[6,2])), "Recollection",
          as.double(pull(exp1__rec_hit_figure_data[6,3])), as.double(pull(exp1__rec_hit_figure_data[6,4])),
          as.character(pull(exp1__fam_hit_figure_data[1,1])), 
          as.character(pull(exp1__fam_hit_figure_data[1,2])), "Familiarity",
          as.double(pull(exp1__fam_hit_figure_data[1,3])), as.double(pull(exp1__fam_hit_figure_data[1,4])),
          as.character(pull(exp1__fam_hit_figure_data[2,1])), 
          as.character(pull(exp1__fam_hit_figure_data[2,2])), "Familiarity",
          as.double(pull(exp1__fam_hit_figure_data[2,3])), as.double(pull(exp1__fam_hit_figure_data[2,4])),
          as.character(pull(exp1__fam_hit_figure_data[3,1])), 
          as.character(pull(exp1__fam_hit_figure_data[3,2])), "Familiarity",
          as.double(pull(exp1__fam_hit_figure_data[3,3])), as.double(pull(exp1__fam_hit_figure_data[3,4])),
          as.character(pull(exp1__fam_hit_figure_data[4,1])), 
          as.character(pull(exp1__fam_hit_figure_data[4,2])), "Familiarity",
          as.double(pull(exp1__fam_hit_figure_data[4,3])), as.double(pull(exp1__fam_hit_figure_data[4,4])),
          as.character(pull(exp1__fam_hit_figure_data[5,1])), 
          as.character(pull(exp1__fam_hit_figure_data[5,2])), "Familiarity",
          as.double(pull(exp1__fam_hit_figure_data[5,3])), as.double(pull(exp1__fam_hit_figure_data[5,4])),
          as.character(pull(exp1__fam_hit_figure_data[6,1])), 
          as.character(pull(exp1__fam_hit_figure_data[6,2])), "Familiarity",
          as.double(pull(exp1__fam_hit_figure_data[6,3])), as.double(pull(exp1__fam_hit_figure_data[6,4])),
          as.character(pull(exp1__guess_hit_figure_data[1,1])),
          as.character(pull(exp1__guess_hit_figure_data[1,2])), "Guessing",
          as.double(pull(exp1__guess_hit_figure_data[1,3])), as.double(pull(exp1__guess_hit_figure_data[1,4])),
          as.character(pull(exp1__guess_hit_figure_data[2,1])),
          as.character(pull(exp1__guess_hit_figure_data[2,2])), "Guessing",
          as.double(pull(exp1__guess_hit_figure_data[2,3])), as.double(pull(exp1__guess_hit_figure_data[2,4])),
          as.character(pull(exp1__guess_hit_figure_data[3,1])),
          as.character(pull(exp1__guess_hit_figure_data[3,2])), "Guessing",
          as.double(pull(exp1__guess_hit_figure_data[3,3])), as.double(pull(exp1__guess_hit_figure_data[3,4])),
          as.character(pull(exp1__guess_hit_figure_data[4,1])),
          as.character(pull(exp1__guess_hit_figure_data[4,2])), "Guessing",
          as.double(pull(exp1__guess_hit_figure_data[4,3])), as.double(pull(exp1__guess_hit_figure_data[4,4])),
          as.character(pull(exp1__guess_hit_figure_data[5,1])),
          as.character(pull(exp1__guess_hit_figure_data[5,2])), "Guessing",
          as.double(pull(exp1__guess_hit_figure_data[5,3])), as.double(pull(exp1__guess_hit_figure_data[5,4])),
          as.character(pull(exp1__guess_hit_figure_data[6,1])),
          as.character(pull(exp1__guess_hit_figure_data[6,2])), "Guessing",
          as.double(pull(exp1__guess_hit_figure_data[6,3])), as.double(pull(exp1__guess_hit_figure_data[6,4]))) %>%
          transform(resp_optiononseOption = factor(resp_optiononseOption, levels=c("RFG","RFBG","RF_Ratings"))) %>%
          transform(rfg = factor(rfg, levels=c("Recollection","Familiarity","Guessing"))) %>%
          transform(stimuliFormat = factor(stimuliFormat, levels=c("Words","Pictures")))
##    Hit figure:
      exp1__hit_figure <- ggplot(exp1__hit_figure_data, aes(x = stimuliFormat, y = emmean, fill = rfg)) +
          scale_fill_manual("legend", values = c("Recollection" = "#1B4251", "Familiarity" = "#6A6C93",
                                                 "Guessing" = "#D491CA")) + 
          geom_col(position = position_dodge()) +
          geom_errorbar(aes(ymin = pmax(emmean-SE, 0), ymax = emmean+SE), width = 0.2, size = 0.3, 
                        position = position_dodge(0.9)) +
          facet_wrap(~resp_optiononseOption, strip.position = "bottom") +
          labs(x = "resp_optiononse-option condition", y = "Mean proportion of hits") +
          scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
          theme_classic() +    # Removes grey background and grid lines. 
          theme(
              strip.placement = "outside",
              strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
              axis.title.x = element_text(vjust=-4),    # Move x-axis label further away from the figure.
              axis.title.y = element_text(vjust=6),     # Move y-axis label further away from the figure.
              axis.text.x = element_text(size = 9),
              axis.text.y = element_text(size = 9),
              legend.background = element_rect(fill = "white", size = 0.2, linetype = "solid", colour = "black"),
              legend.title = element_blank(),
              legend.position = c(0.5, 0.896),
              legend.margin = margin(6, 6, 6, 6),
              legend.spacing.y = unit(-1, "pt"),
              plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
              plot.margin = margin(20, 20, 24, 30))
###################################################################################################################
##    Rec / Fam / Guess FAs figure:                                                                              ##
###################################################################################################################
      exp1__rec_FA_figure_data <- as.tibble(exp1__anova_prop_rec_FA_interaction_emmeans) %>%
          select(-df, -lower.CL, -upper.CL)
      exp1__fam_FA_figure_data <- as.tibble(exp1__anova_prop_fam_FA_interaction_emmeans) %>%
          select(-df, -lower.CL, -upper.CL)
      exp1__guess_FA_figure_data <- as.tibble(exp1__anova_prop_guess_FA_interaction_emmeans) %>%
          select(-df, -lower.CL, -upper.CL)
  
      exp1__FA_figure_data <- tribble(~"resp_optiononseOption", ~"stimuliFormat", ~"rfg", ~"emmean", ~"SE",
          as.character(pull(exp1__rec_FA_figure_data[1,1])), 
          as.character(pull(exp1__rec_FA_figure_data[1,2])), "Recollection",
          as.double(pull(exp1__rec_FA_figure_data[1,3])), as.double(pull(exp1__rec_FA_figure_data[1,4])),
          as.character(pull(exp1__rec_FA_figure_data[2,1])), 
          as.character(pull(exp1__rec_FA_figure_data[2,2])), "Recollection",
          as.double(pull(exp1__rec_FA_figure_data[2,3])), as.double(pull(exp1__rec_FA_figure_data[2,4])),
          as.character(pull(exp1__rec_FA_figure_data[3,1])), 
          as.character(pull(exp1__rec_FA_figure_data[3,2])), "Recollection",
          as.double(pull(exp1__rec_FA_figure_data[3,3])), as.double(pull(exp1__rec_FA_figure_data[3,4])),
          as.character(pull(exp1__rec_FA_figure_data[4,1])), 
          as.character(pull(exp1__rec_FA_figure_data[4,2])), "Recollection",
          as.double(pull(exp1__rec_FA_figure_data[4,3])), as.double(pull(exp1__rec_FA_figure_data[4,4])),
          as.character(pull(exp1__rec_FA_figure_data[5,1])), 
          as.character(pull(exp1__rec_FA_figure_data[5,2])), "Recollection",
          as.double(pull(exp1__rec_FA_figure_data[5,3])), as.double(pull(exp1__rec_FA_figure_data[5,4])),
          as.character(pull(exp1__rec_FA_figure_data[6,1])), 
          as.character(pull(exp1__rec_FA_figure_data[6,2])), "Recollection",
          as.double(pull(exp1__rec_FA_figure_data[6,3])), as.double(pull(exp1__rec_FA_figure_data[6,4])),
          as.character(pull(exp1__fam_FA_figure_data[1,1])), 
          as.character(pull(exp1__fam_FA_figure_data[1,2])), "Familiarity",
          as.double(pull(exp1__fam_FA_figure_data[1,3])), as.double(pull(exp1__fam_FA_figure_data[1,4])),
          as.character(pull(exp1__fam_FA_figure_data[2,1])), 
          as.character(pull(exp1__fam_FA_figure_data[2,2])), "Familiarity",
          as.double(pull(exp1__fam_FA_figure_data[2,3])), as.double(pull(exp1__fam_FA_figure_data[2,4])),
          as.character(pull(exp1__fam_FA_figure_data[3,1])), 
          as.character(pull(exp1__fam_FA_figure_data[3,2])), "Familiarity",
          as.double(pull(exp1__fam_FA_figure_data[3,3])), as.double(pull(exp1__fam_FA_figure_data[3,4])),
          as.character(pull(exp1__fam_FA_figure_data[4,1])), 
          as.character(pull(exp1__fam_FA_figure_data[4,2])), "Familiarity",
          as.double(pull(exp1__fam_FA_figure_data[4,3])), as.double(pull(exp1__fam_FA_figure_data[4,4])),
          as.character(pull(exp1__fam_FA_figure_data[5,1])), 
          as.character(pull(exp1__fam_FA_figure_data[5,2])), "Familiarity",
          as.double(pull(exp1__fam_FA_figure_data[5,3])), as.double(pull(exp1__fam_FA_figure_data[5,4])),
          as.character(pull(exp1__fam_FA_figure_data[6,1])), 
          as.character(pull(exp1__fam_FA_figure_data[6,2])), "Familiarity",
          as.double(pull(exp1__fam_FA_figure_data[6,3])), as.double(pull(exp1__fam_FA_figure_data[6,4])),
          as.character(pull(exp1__guess_FA_figure_data[1,1])), 
          as.character(pull(exp1__guess_FA_figure_data[1,2])), "Guessing",
          as.double(pull(exp1__guess_FA_figure_data[1,3])), as.double(pull(exp1__guess_FA_figure_data[1,4])),
          as.character(pull(exp1__guess_FA_figure_data[2,1])), 
          as.character(pull(exp1__guess_FA_figure_data[2,2])), "Guessing",
          as.double(pull(exp1__guess_FA_figure_data[2,3])), as.double(pull(exp1__guess_FA_figure_data[2,4])),
          as.character(pull(exp1__guess_FA_figure_data[3,1])), 
          as.character(pull(exp1__guess_FA_figure_data[3,2])), "Guessing",
          as.double(pull(exp1__guess_FA_figure_data[3,3])), as.double(pull(exp1__guess_FA_figure_data[3,4])),
          as.character(pull(exp1__guess_FA_figure_data[4,1])), 
          as.character(pull(exp1__guess_FA_figure_data[4,2])), "Guessing",
          as.double(pull(exp1__guess_FA_figure_data[4,3])), as.double(pull(exp1__guess_FA_figure_data[4,4])),
          as.character(pull(exp1__guess_FA_figure_data[5,1])), 
          as.character(pull(exp1__guess_FA_figure_data[5,2])), "Guessing",
          as.double(pull(exp1__guess_FA_figure_data[5,3])), as.double(pull(exp1__guess_FA_figure_data[5,4])),
          as.character(pull(exp1__guess_FA_figure_data[6,1])), 
          as.character(pull(exp1__guess_FA_figure_data[6,2])), "Guessing",
          as.double(pull(exp1__guess_FA_figure_data[6,3])), as.double(pull(exp1__guess_FA_figure_data[6,4]))) %>%
          transform(resp_optiononseOption = factor(resp_optiononseOption, levels=c("RFG","RFBG","RF_Ratings"))) %>%
          transform(rfg = factor(rfg, levels=c("Recollection","Familiarity","Guessing"))) %>%
          transform(stimuliFormat = factor(stimuliFormat, levels=c("Words","Pictures")))
              
      exp1__FA_figure <- ggplot(exp1__FA_figure_data, aes(x = stimuliFormat, y = emmean, fill = rfg)) +
          scale_fill_manual("legend", values = c("Recollection" = "#1B4251", "Familiarity" = "#6A6C93", 
                                                 "Guessing" = "#D491CA")) + 
          geom_col(position = position_dodge()) +
          geom_errorbar(aes(ymin = emmean-SE, ymax = emmean+SE), width = 0.2, size = 0.3, 
                        position = position_dodge(0.9)) +
          facet_wrap(~resp_optiononseOption, strip.position = "bottom") +
          labs(x = "resp_optiononse-option condition", y = "Mean proportion of FAs") +
          scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) + 
          theme_classic() +
          theme(
              strip.placement = "outside",
              strip.background = element_rect(fill = "white", size = 0.5, linetype = "solid", colour = "black"),
              axis.title.x = element_text(vjust=-4),    # Move x-axis label further away from the figure.
              axis.title.y = element_text(vjust=6),     # Move y-axis label further away from the figure.
              axis.text.x = element_text(size = 9),
              axis.text.y = element_text(size = 9),
              legend.background = element_rect(fill = "white", size = 0.2, linetype = "solid", colour = "black"),
              legend.title = element_blank(),
              legend.position = c(0.5, 0.896),
              legend.margin = margin(6, 6, 6, 6),
              legend.spacing.y = unit(-1, "pt"),
              plot.background = element_rect(size = 0.5, linetype = 'solid', colour = "black"),
              plot.margin = margin(20, 20, 24, 30))
```



#### PSE and the availability of different resp_optiononse options:
To determine whether the availability of different options had an impact on picture superiority within the current paradigm, the main effects of response option were also examined in the aforementioned ANOVAs. Discriminability (*d'*) between hits and FAs showed no significant main effect of resp_optiononse option, supporting the hypothesis that a PSE would be evident in each of the resp_optiononse option conditions. resp_optiononse bias (*c*) scores did show a main effect of resp_optiononse option though, `r exp1__apa_anova_prop_c$full$resp_optiononseOption`; those in the RF-Ratings condition (`r exp1__rfr_c_mean`) showed higher c-scores (and thus a more conservative resp_optiononse bias) than those in the RFG condition (`r exp1__rfg_c_mean`), `r exp1__rfg_rfr_c_ttest`. This indicates subjects were less likely to resp_optionond *Old* when they were required to provide more detailed follow-up recognition judgements (i.e., using separate 0-5 scales for R and F), compared to simply selecting one of three options (R,F, or G). This again supports the notion of avoidance from participants when they were required to provide two separate ratings. The ANOVAs on the proportion of hits, FAs, and overall recognition also mostly supported our hypothesis that a PSE would be evident in each of the resp_optiononse option conditions. While the ANOVAs on the proportion of FAs and overall recognition showed no significant main effects of resp_optiononse option, there was a significant main effect for the proportion of hits, `r exp1__apa_anova_prop_hit$full$resp_optiononseOption`, with the RFG group (`r exp1__rfg_prop_hit_mean`) showing more hits than the RF-Ratings group (`r exp1__rfratings_prop_hit_mean`), `r exp1__rfg_rfr_hit_ttest`. This unexpected result may also reflect the conservative resp_optiononse bias of those in the RF-Ratings group, whereby fewer total *Old* resp_optiononses necessitates fewer hits as a result. However, a lack of differences between groups for FAs and overall recognition indicates a comparable PSE across each of the resp_optiononse option groups. 

With regard to rates of R and F, there was a significant main effect of resp_optiononse-option for R hits, `r exp1__apa_anova_prop_rec_hit$full$resp_optiononseOption`; the RF-Ratings group (`r exp1__rfr_rec_hit_mean`) showed significantly more R hits compared to both the RFG-group (`r exp1__rfg_rec_hit_mean`), `r exp1__rfg_rfr_rec_hit_ttest`, and the RFBG-group (`r exp1__rfbg_rec_hit_mean`), `r exp1__rfbg_rfr_rec_hit_ttest`. R FA's also exhibited an identical pattern; a significant main effect of resp_optiononse-option, `r exp1__apa_anova_prop_rec_FA$full$resp_optiononseOption`, showed that those in the RF-Ratings group (`r exp1__rfr_rec_FA_mean`) produced more Recollection FAs than both the RFG-group (`r exp1__rfg_rec_FA_mean`), `r exp1__rfg_rfr_rec_FA_ttest`, and RFBG-group (`r exp1__rfbg_rec_FA_mean`), `r exp1__rfbg_rfr_rec_FA_ttest`). 
These findings align with those above to suggest a more conservative resp_optiononse bias in the RF-Ratings group; participants were more likely to resp_optionond *Old* in the RF-Ratings condition when they experienced high certainty in their recognition - regardless of whether or not that recognition was accurate or false. 

&nbsp;

The significant interaction for F hits showed that word stimuli produced significantly more F hits in the RF-Ratings group (`r exp1__rfr_words_fam_hit_mean`) compared to the RFG group (`r exp1__rfg_words_fam_hit_mean`), `r exp1__apa_anova_prop_fam_hit_interaction_pairwise_resp_optionoption$statistic$Words_RFG_RF_Ratings`. An identical pattern was also observed for pictures between the RF-Ratings group (`r exp1__rfr_pics_fam_hit_mean`) and RFG group (`r exp1__rfg_pics_fam_hit_mean`), `r exp1__apa_anova_prop_fam_hit_interaction_pairwise_resp_optionoption$statistic$Pictures_RFG_RF_Ratings`, however, F hits in the RF-Ratings group were also higher than the RFBG group (`r exp1__rfbg_pics_fam_hit_mean`) when the stimuli were pictures, `r exp1__apa_anova_prop_fam_hit_interaction_pairwise_resp_optionoption$statistic$Pictures_RFBG_RF_Ratings`. The RFBG group (`r exp1__rfbg_pics_fam_hit_mean`) also showed a significantly higher number of F hits compared to the RFG group (`r exp1__rfg_pics_fam_hit_mean`), `r exp1__apa_anova_prop_fam_hit_interaction_pairwise_resp_optionoption$statistic$Pictures_RFG_RFBG`. There was no significant main effect of resp_optiononse-option for F FAs. Such findings suggest that the proportion of F resp_optiononses increases when participants are given the option to report *Both* - either explicitly, or from rating high on both rating scales. 

&nbsp;

Finally, the significant interaction for G hits demonstrated that word stimuli produced significantly fewer G hits in the RF-Ratings group (`r exp1__rfr_words_guess_hit_mean`) compared to both the RFG group (`r exp1__rfg_words_guess_hit_mean`), `r exp1__apa_anova_prop_guess_hit_interaction_pairwise_resp_optionoption$statistic$Words_RFG_RF_Ratings`, and the RFBG group (`r exp1__rfbg_words_guess_hit_mean`), `r exp1__apa_anova_prop_guess_hit_interaction_pairwise_resp_optionoption$statistic$Words_RFBG_RF_Ratings`. Likewise, pictures also produced significantly fewer G hits in the RF-Ratings group (`r exp1__rfr_pics_guess_hit_mean`) compared to both the RFG group (`r exp1__rfg_pics_guess_hit_mean`), `r exp1__apa_anova_prop_guess_hit_interaction_pairwise_resp_optionoption$statistic$Pictures_RFG_RF_Ratings` and RFBG group (`r exp1__rfbg_pics_guess_hit_mean`), `r exp1__apa_anova_prop_guess_hit_interaction_pairwise_resp_optionoption$statistic$Pictures_RFBG_RF_Ratings`. For G FAs, a significant main effect of resp_optiononse-option, `r exp1__apa_anova_prop_guess_FA$full$resp_optiononseOption` revealed that the RF-ratings group (`r exp1__rfr_guess_FA_mean`) again showed significantly fewer G FAs than both the RFG (`r exp1__rfg_guess_FA_mean`), `r exp1__rfg_rfr_guess_FA_ttest`, and RFBG groups (`r exp1__rfbg_guess_FA_mean`), `r exp1__rfbg_rfr_guess_FA_ttest`. These findings again align with the previous results that suggest those in the RF-Ratings group resp_optiononded conservatively overall, and were less likely to resp_optionond *Old* than the other groups unless they felt a high level of certainty. 
